### ISSUE TITLE
`fetchWithCompletion` should fill whole object

### ISSUE THREAD

**Issue by lifcio** [Syncano/syncano4-ios#1]
I should be able to:
```objc
book = [Book new]; 
book.objectId = @(10); 
[book fetchWithCompletion:...];`
```
It should have the same effect as doing:
```objc
predicate = [SCPredicate whereKey:@"id" isEqualToNumber:@10];
[[Book please] giveMeDataObjectsWithPredicate:predicate ...];
```

Right now `fetch...` updates only 
```objc
 object.objectId = responseObject[@"id"];
 object.created_at = responseObject[@"created_at"];
 object.links = responseObject[@"links"];
 object.updated_at = responseObject[@"updated_at"];
 object.revision = responseObject[@"revision"];
```

**Comment by jaskooo** [comment]
What about relations to another objects here?

**Comment by lifcio** [comment]
Hmm... The problem is because of lack of the parameters dictionary with options you could pass?

I would assume no relations in this case. So you would download a book, and an empty author object (with just ID - you will get it when fetching book).
So when I do
```objc
[book new]
[book fetch]
```
I have just the book. If I want author too, I can do
```objc
[book.author fetch]
```

Sounds reasonable?

**Comment by jaskooo** [comment]
ok let's do it like that :)

**Comment by jaskooo** [comment]
But there is another case of using this method. Saving.
Let say that i have created object Author locally on device and another object Book which has a reference to this newly created Author object. When i am saving this Book to server and updating it with response JSON i am loosing this relation.

**Comment by lifcio** [comment]
Yeah, but I think that's how it should be. Cause on the other hand you may have book and author pair, and someone will delete the author on one device - when you fetch again with empty author coming from Syncano, you should delete the relation.

Otherwise, we could do it better and check for revision. If revision of `Author` is not set, it means object is only local, not saved to server, so don't replace it.

Guessing which version is correct - server one or local one is quite complex, so maybe for now we go with simple - no resolving relations on save - and we will add it later?

**Comment by jaskooo** [comment]
```Author *author = [Author new];
    author.firstname = @"Tadeusz";
    author.secondname = @"Iksiński";

    Book *book = [Book new];
    book.title = @"new title with author";
    book.numOfPages = @1134;
    book.author = author;
    [book saveWithCompletionBlock:^(NSError *error) {
   }];
```
Now while you saving book , author is saved automatically.
If we fill book with only id of the author we will loose reference to author object above

**Comment by lifcio** [comment]
But save is different from fetch, right? We're talking about `fetch` here, so it won't affect fetch?

But if you think it's doable and would work in a similar way in fetch as it does in save, we could go with downloading relation objects with fetch as well - but it works only up to 1 level, right? If author would have relation to `City` we wouldn't download it?

**Comment by jaskooo** [comment]
addedfe fixed this
