### ISSUE TITLE
Passing Array to SCPleaseParameterFields

### ISSUE THREAD

**Issue by lifcio** [Syncano/syncano4-ios#8]
If I understand correctly, since the key name is "fields" we would expect to have array passed here. But unfortunately, default AFNetworking query parsing, makes from dictionary
```objc
@{
   @"fields":@[@"title"]
};
```
following query string: `fields[]=title`, so the whole request looks like `https://api.syncano.rocks/v1/instances/mariusz/classes/book/objects/?fields[]=title`.
If I pass more than one value, it doesn't change much, it just makes from it 
`fields[]=title&fields[]=subtitle` and `https://api.syncano.rocks/v1/instances/mariusz/classes/book/objects/?fields[]=title&fields[]=subtitle`.

Possible solution:
use `setQueryStringSerializationWithBlock:` method on `AFURLRequestSerialization` to define own serializer which wound handle arrays correctly.

Or, simpler solution, without modifying AFNetworking query serialization, just manually convert passed array into strings separated by comma, e.g.
```objc
- (void)giveMeDataObjectsWithParameters:(NSDictionary *)parameters completion:(SCDataObjectsCompletionBlock)completion {
    if ([parameters[SCPleaseParameterFields] isKindOfClass:[NSArray class]] == YES) {
        NSArray *fieldsArray = parameters[SCPleaseParameterFields];
        NSString *fields = [fieldsArray componentsJoinedByString:@","];
        NSMutableDictionary *parametersCopy = [parameters mutableCopy];
        [parametersCopy setObject:fields forKey:SCPleaseParameterFields];
        self.parameters = parametersCopy;
    } else {
        self.parameters = parameters;
    }
    self.predicate = nil;
    [self getDataObjectFromAPIWithCompletion:completion];
}
```

**Comment by jaskooo** [comment]
Ok i think i will cover this with second solution :) Thanks
